from configs.pipeline_cfg import *

FONT_SIZE = 16
BACKGROUND_COLOR = (0, 0, 0)
FONT_COLOR = (255, 255, 255)

OFFSET_SIZE = 2
CELL_SIZE = 8
VIEWS_IN_ROW = 3

LAYOUT = (CHANNELS_NUM // VIEWS_IN_ROW,
          min(VIEWS_IN_ROW, CHANNELS_NUM))

DISPLAY_SIZE = (LAYOUT[1] * (ENV_VIEW_SIZE[0] * CELL_SIZE) + (LAYOUT[1] - 1) * OFFSET_SIZE,
                LAYOUT[0] * (ENV_VIEW_SIZE[1] * CELL_SIZE) + (LAYOUT[0] - 1) * OFFSET_SIZE)
