ENV_MAP = "BuildMarines"
ENV_VIEW_SIZE = (16, 16)
ENV_MAP_SIZE = (48, 48)

LEARNING_RATE = 1e-3
MERGE_FREQ = 10
BATCH_SIZE = 3
STEPS = 2
GAMMA = 0.99

MEMORY_CAPACITY = 100000
MIN_MEMORY_CAPACITY = 10000

EPSILON_MAX = 1.0
EPSILON_MIN = 0.02
EPSILON_DECAY = 0.99

CHANNELS_NUM = 6
AGENT_VIEW_SIZE = (16, 16)
DQN_INPUT_SHAPE = (CHANNELS_NUM, AGENT_VIEW_SIZE[0], AGENT_VIEW_SIZE[1])
DQN_OUTPUT_SHAPE = (10,)

ENV_ACTION_SHAPE = (1,)
ENV_STATE_SHAPE = DQN_INPUT_SHAPE
ENV_REWARD_SHAPE = (1,)
ENV_DONE_SHAPE = (1,)
