ENV_MAP = "BuildMarines"
ENV_VIEW_SIZE = (24, 24)
ENV_MAP_SIZE = (48, 48)

LEARNING_RATE = 1e-2
MERGE_FREQ = 1
BATCH_SIZE = 16
STEPS = 10
GAMMA = 0.99

MEMORY_CAPACITY = 10001
MIN_MEMORY_CAPACITY = 100

EPSILON_MAX = 0.3
EPSILON_MIN = 0.02
EPSILON_DECAY = 0.99

CHANNELS_NUM = 4
AGENT_VIEW_SIZE = ENV_VIEW_SIZE
DQN_INPUT_SHAPE = (CHANNELS_NUM, AGENT_VIEW_SIZE[0], AGENT_VIEW_SIZE[1])
DQN_OUTPUT_SHAPE = (10,)

ENV_ACTION_SHAPE = (1,)
ENV_STATE_SHAPE = DQN_INPUT_SHAPE
ENV_REWARD_SHAPE = (1,)
ENV_DONE_SHAPE = (1,)
